### ISSUE TITLE
REKEYING BASH

### ISSUE THREAD

**Issue by Cylakk** [ChoiceCoin/Algorand-Protocol#1]
Details

First Prize: 80,000.00 Choice | Gold Badge
Second Prize: 50,000.00 Choice | Silver Badge
Third Prize: 20,000.00 Choice | Bronze Badge

Deadline: February 5, 7:00PM PT

The goal of this bash is to rekey your Algorand wallet account to a multisignature account.
(Rekeying is a feature on the Algorand blockchain, which enables an account holder to retain
same public address while effectively rotating the authentic private spending keys.)

For example; Ezhia private account key has been compromised, and she needs to change her
private keys, maintain good security and also give access to trusted third parties of her choice
without changing her public address, which involves updating everyone who has previously
saved her address.

Instead Ezhia can simply issue a special transaction that registers a new private key, as the
approval method for her existing public address.
Also she can rekey her account to a multisignature account, which is convenient and her
security is highly maintained.

Requirements
The program must be submitted as a pull request in the Rekeying Bash, in the ALGORAND
PROTOCOL folder.

All files submitted must be aggregated in one folder with the title:

[UserName]_REKEYING_Bash, such as Cylak_REKEY_Bash.

The PR should be titled [UserName]_Bash.

The pull request for the program must be made before the task Deadline.

The program must be run on the Algorand TestNet.

Any TestNet Algo or Choice Asset ID may be used in the program.

You must provide screenshots or a video link for the program, but a YouTube link is the best.
The program should include a ReadMe file with the problem, solution, description, and run
steps.

As few scripts and files as possible should be used.

Additional Information

Winners will be selected based on clarity, simplicity, functionality, and design.
You can learn more about REKEYING at this

https://developer.algorand.org/docs/get-details/accounts/rekey/

For more questions or comments, please ask in Discord.

**Comment by Ifebisi** [comment]
Great job!  So glad to know this project

**Comment by Benqadosh** [comment]
Really amazing project, check it out guyys 🚀
